(() => {
  "use strict";

  // ---------- utils ----------
  const qs = (s, root = document) => root.querySelector(s);
  const qsa = (s, root = document) => Array.from(root.querySelectorAll(s));
  const on = (el, ev, fn, opts) => el && el.addEventListener(ev, fn, opts);

  const normalize = (s) => String(s || "").toLowerCase().trim();
  const escapeHTML = (s) =>
    String(s)
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#39;");

  async function fetchJson(url) {
    const res = await fetch(url, { cache: "force-cache" });
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
    return res.json();
  }

  // ---------- header / menu ----------
  function initMenu() {
    const menuBtn = qs("#menuBtn");
    const mobileMenu = qs("#mobileMenu");
    if (!menuBtn || !mobileMenu) return;

    const setMenu = (open) => {
      menuBtn.setAttribute("aria-expanded", open ? "true" : "false");
      mobileMenu.hidden = !open;
      document.body.classList.toggle("noScroll", open);
    };

    const isOpen = () => menuBtn.getAttribute("aria-expanded") === "true";

    on(menuBtn, "click", () => setMenu(!isOpen()), { passive: true });

    on(
      mobileMenu,
      "click",
      (e) => {
        const a = e.target.closest("a[href^='#']");
        if (a) setMenu(false);
      },
      { passive: true }
    );

    on(window, "keydown", (e) => {
      if (e.key === "Escape") setMenu(false);
    });

    on(document, "click", (e) => {
      if (!isOpen()) return;
      const t = e.target;
      if (menuBtn.contains(t) || mobileMenu.contains(t)) return;
      setMenu(false);
    });

    on(
      window,
      "resize",
      () => {
        if (!isOpen()) return;
        if (window.matchMedia("(min-width: 860px)").matches) setMenu(false);
      },
      { passive: true }
    );
  }

  // ---------- feed ----------
  const CATEGORY_LABEL = {
    news: "News",
    forecast: "Forecasts",
    review: "Reviews",
  };

  function matches(post, filter, query) {
    if (filter !== "all" && post.category !== filter) return false;
    if (!query) return true;

    const hay = [
      post.title,
      post.summary,
      (post.tags || []).join(" "),
      post.date,
      post.category,
    ]
      .map(normalize)
      .join(" | ");

    return hay.includes(query);
  }

  function byDateDesc(a, b) {
    return String(b.date).localeCompare(String(a.date));
  }

  function renderFeed({ feedList, posts, filter, query }) {
    const view = posts.filter((p) => matches(p, filter, query)).sort(byDateDesc);

    if (!view.length) {
      feedList.innerHTML = `<div class="tile"><div class="muted">No results.</div></div>`;
      return;
    }

    feedList.innerHTML = view
      .map((p) => {
        const cat = CATEGORY_LABEL[p.category] || p.category;
        const tags = (p.tags || [])
          .slice(0, 6)
          .map((t) => `<span class="tag">${escapeHTML(t)}</span>`)
          .join("");

        // IMPORTANT: link to SEO page (generated by GitHub Actions)
        const href = `p/${encodeURIComponent(p.slug)}/`;

        return `
          <article class="postCard" data-slug="${escapeHTML(p.slug)}">
            <div class="postCard__top">
              <span class="kicker">${escapeHTML(cat)} • ${escapeHTML(p.date)}</span>
            </div>
            <h3 class="postCard__title">${escapeHTML(p.title)}</h3>
            <p class="postCard__summary">${escapeHTML(p.summary || "")}</p>
            <div class="postCard__bottom">
              <div class="tags">${tags}</div>
              <a class="btn btn--ghost btn--sm" href="${href}">Read</a>
            </div>
          </article>
        `;
      })
      .join("");
  }

  async function initFeed() {
    const feedList = qs("#feedList");
    const qInput = qs("#q");
    const filterBtns = qsa(".chip[data-filter]");
    if (!feedList) return;

    let posts = [];
    let filter = "all";
    let query = "";

    const setActive = (btn) => {
      for (const b of filterBtns) b.classList.remove("isActive");
      btn.classList.add("isActive");
    };

    for (const b of filterBtns) {
      on(
        b,
        "click",
        () => {
          filter = b.dataset.filter || "all";
          setActive(b);
          renderFeed({ feedList, posts, filter, query });
        },
        { passive: true }
      );
    }

    if (qInput) {
      on(
        qInput,
        "input",
        () => {
          query = normalize(qInput.value);
          renderFeed({ feedList, posts, filter, query });
        },
        { passive: true }
      );
    }

    try {
      const data = await fetchJson("posts/index.json");
      posts = Array.isArray(data.posts) ? data.posts : [];
      renderFeed({ feedList, posts, filter, query });
    } catch {
      feedList.innerHTML =
        `<div class="tile"><div class="muted">Failed to load feed. Check <code>posts/index.json</code>.</div></div>`;
    }
  }

  // ---------- anchors smooth scroll ----------
  function initAnchors() {
    const reduce = window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false;

    on(document, "click", (e) => {
      const a = e.target.closest("a[href^='#']");
      if (!a) return;

      const id = a.getAttribute("href");
      if (!id || id === "#") return;

      const el = qs(id);
      if (!el) return;

      e.preventDefault();
      el.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "start" });
      history.pushState(null, "", id);
    });
  }

  // ---------- init ----------
  (function init() {
    const y = qs("#y");
    if (y) y.textContent = String(new Date().getFullYear());

    initMenu();
    initAnchors();
    initFeed();
  })();
})();
